# Generated by Django 4.1.3 on 2022-11-14 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categories')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Other_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(editable=False, max_length=200, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('add_info', models.TextField(blank=True, editable=False, max_length=500)),
                ('rent', models.IntegerField(editable=False)),
                ('images', models.ImageField(editable=False, upload_to='photos/house')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, editable=False, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=5, editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(editable=False, max_length=200, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('add_info', models.TextField(blank=True, editable=False, max_length=500)),
                ('rent', models.IntegerField(editable=False)),
                ('bedroom', models.IntegerField(editable=False)),
                ('bathroom', models.IntegerField(editable=False)),
                ('builtup', models.IntegerField(editable=False)),
                ('capacity', models.IntegerField(editable=False)),
                ('type', models.CharField(blank=True, editable=False, max_length=200)),
                ('furnish', models.CharField(blank=True, editable=False, max_length=200)),
                ('state', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('place', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('street', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('images', models.ImageField(editable=False, null=True, upload_to='photos/house')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Furn_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(editable=False, max_length=200, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('add_info', models.TextField(blank=True, editable=False, max_length=500)),
                ('rent', models.IntegerField(editable=False)),
                ('images', models.ImageField(editable=False, upload_to='photos/house')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, editable=False, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=4, editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('add_info', models.TextField(blank=True, editable=False, max_length=500)),
                ('rent', models.IntegerField(editable=False)),
                ('brand', models.CharField(blank=True, editable=False, max_length=200)),
                ('driven', models.IntegerField(editable=False)),
                ('own', models.CharField(blank=True, editable=False, max_length=200)),
                ('fuel', models.CharField(blank=True, editable=False, max_length=200)),
                ('images', models.ImageField(editable=False, upload_to='photos/house')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bike_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('add_info', models.TextField(blank=True, editable=False, max_length=500)),
                ('rent', models.IntegerField(editable=False)),
                ('brand', models.CharField(blank=True, editable=False, max_length=200)),
                ('driven', models.IntegerField(editable=False)),
                ('own', models.CharField(blank=True, editable=False, max_length=200)),
                ('images', models.ImageField(editable=False, upload_to='photos/house')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
