# Generated by Django 4.1.2 on 2022-11-03 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_product',
            name='add_info',
            field=models.TextField(blank=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='bike_product',
            name='brand',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='bike_product',
            name='category',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='bike_product',
            name='driven',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bike_product',
            name='images',
            field=models.ImageField(editable=False, upload_to='photos/house'),
        ),
        migrations.AlterField(
            model_name='bike_product',
            name='own',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='bike_product',
            name='rent',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='car_product',
            name='add_info',
            field=models.TextField(blank=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='car_product',
            name='brand',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='car_product',
            name='category',
            field=models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='car_product',
            name='driven',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='car_product',
            name='fuel',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='car_product',
            name='images',
            field=models.ImageField(editable=False, upload_to='photos/house'),
        ),
        migrations.AlterField(
            model_name='car_product',
            name='own',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='car_product',
            name='rent',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='car_product',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='furn_product',
            name='ad_title',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='furn_product',
            name='add_info',
            field=models.TextField(blank=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='furn_product',
            name='category',
            field=models.ForeignKey(default=4, editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='furn_product',
            name='images',
            field=models.ImageField(editable=False, upload_to='photos/house'),
        ),
        migrations.AlterField(
            model_name='furn_product',
            name='rent',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='furn_product',
            name='type',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='furn_product',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house_product',
            name='ad_title',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='house_product',
            name='add_info',
            field=models.TextField(blank=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='house_product',
            name='bathroom',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='house_product',
            name='bedroom',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='house_product',
            name='builtup',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='house_product',
            name='capacity',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='house_product',
            name='furnish',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='house_product',
            name='images',
            field=models.ImageField(editable=False, upload_to='photos/house'),
        ),
        migrations.AlterField(
            model_name='house_product',
            name='rent',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='house_product',
            name='type',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='other_product',
            name='ad_title',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='other_product',
            name='add_info',
            field=models.TextField(blank=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='other_product',
            name='category',
            field=models.ForeignKey(default=5, editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='other_product',
            name='images',
            field=models.ImageField(editable=False, upload_to='photos/house'),
        ),
        migrations.AlterField(
            model_name='other_product',
            name='rent',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='other_product',
            name='type',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='other_product',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='All_Products',
        ),
    ]
