# Generated by Django 4.1.3 on 2022-11-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_house_product_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house_product',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='house_product',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='house_product',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='house_product',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
