# Generated by Django 4.1.3 on 2022-11-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_bike_product_city_bike_product_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
