# Generated by Django 4.1.3 on 2022-11-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_house_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_product',
            name='ad_title',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
