# Generated by Django 4.1.3 on 2022-11-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_bike_product_brand_alter_bike_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_product',
            name='add_info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bike_product',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bike_product',
            name='driven',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bike_product',
            name='images',
            field=models.ImageField(null=True, upload_to='photos/house'),
        ),
        migrations.AlterField(
            model_name='bike_product',
            name='own',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bike_product',
            name='rent',
            field=models.IntegerField(null=True),
        ),
    ]
